# Generated by Django 2.2.7 on 2019-12-01 01:32

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.UUIDField(default=api.models._dashless_uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
